### ISSUE TITLE
Item not in unlock list

### ISSUE THREAD

**Issue by DeafKhan** [stimm4711/GloomhavenCampaignTracker#3]
It is possible to unlock item #45 prior to reaching prosperity level 6, but there appears to be no way to add it to the item store.

**Comment by stimm4711** [comment]
If you get the item, you can add it to a character by its number. Go to the character item sheet and select the "123" button and enter the number of the item (45). If the character sells the item, you will find it in store.
If it is an item design, it is not possible because I didn't know you can get a prosperity item as a design. Please let me know if that is the case.

**Comment by DeafKhan** [comment]
Thanks for the information. It was the first case that I am dealing with,
so that should cover the issue.

We use the tracker just to keep track of unlocks, not any character
specific progress, items, etc, so that's how I missed it. Perhaps it would
still be worth considering being able to add items directly to the shop as
a feature for the future.

Thanks again!
